<?php

/**
 * @file
 * 
 * This module enable the users connect with Sina Weibo.
 * 
 */

use Drupal\sina\sae\SaeTClientV2;


/**
 * Implements hook_menu().
 */
function sina_menu() {  
	$items['admin/config/people/sina'] = array(
		'title' => 'Sina Weibo Login',
		'description' => 'Configure required settings for Sina Weibo integration',
    'route_name' => 'sina.admin',
    'weight' => 10, 
	);
  return $items;
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function sina_form_user_form_alter(&$form, $form_state) {
	$account = $form_state['controller']->getEntity();
	
	$wid = '';
	$wba = \Drupal::service('sina.manager')->findByUid($account->id());
	if (!empty($wba)) {
		$wid = $wba->weibo_uid;
	}
	
	$form['weibo'] = array(
    '#type' => 'details',
    '#title' => t('Weibo settings'),
    '#weight' => 5,
	);
	$form['weibo']['weibo_account'] = array(
    '#type' => 'textfield',
    '#title' => t('Weibo account'),
    '#default_value' => $wid,
    '#description' => t('Bind this account with a Sina Weibo Account.'),
  );  
  $form['actions']['submit']['#submit'][] = 'sina_user_profile_form_submit';
}

/**
 * Submit callback for the user profile form to save the weibo page setting.
 */
function sina_user_profile_form_submit($form, &$form_state) {
	$account = $form_state['controller']->getEntity();
	$wid = $form_state['values']['weibo_account'];
	if ($account->id() && isset($wid)) {
		\Drupal::service('sina.manager')->bind($account->id(), $wid);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function sina_form_user_login_form_alter(&$form, $form_state) {
	$img = \Drupal::config('sina.settings')->get('weibo_button_url', 'http://www.sinaimg.cn/blog/developer/wiki/240.png');
	$form['weibo_login'] = array(
		'#type' => 'item',
		'#description' => l(theme('image', array('uri' => $img)), 'sina/response', array('html' => TRUE)),
	);
}

/**
 * Implements hook_user_view().
 */
function sina_user_view($account) {
	
	$uid = $account->id();

	if ($uid) {

		$wid = t('No Sina Weibo Account Binded.');

		$wba = \Drupal::service('sina.manager')->findByUid($uid);
		if (!empty($wba)) {
			$wid = $wba->weibo_uid;
		}

		$account->content['weibo'] = array(
			'#type' => 'item',
			'#title' => t('Weibo account'),
			'#markup' => $wid,
		);
		
		$account->content['email'] = array(
			'#type' => 'item',
			'#title' => t('Email'),
			'#markup' => $account->getEmail(),
		);
	}
}
